name: Test Flask App

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ENV: test # Set the ENV to test so that an "in memory" database is used
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run tests
      run: PYTHONPATH=$PYTHONPATH:$PWD pytest # Funky pytest stuff
